stages:
  - build
  - test
  - deploy

# Job para compilar la aplicaci贸n
build-job:
  stage: build
  image: gradle:jdk17
  script:
    - echo "Setting permissions for gradlew..."
    - chmod +x gradlew
    - echo "Compiling the code..."
    - ./gradlew clean build
    - echo "Compile complete."

# Job para ejecutar unit tests
unit-test-job:
  stage: test
  image: gradle:jdk17
  script:
    - echo "Running unit tests."
    - ./gradlew test
  artifacts:
    paths:
      - build/test-results/test/ # Ruta donde Gradle guarda los resultados de pruebas unitarias
    reports:
      junit: build/test-results/test/TEST-*.xml # Configura los reportes para que sean accesibles en GitLab CI

# Job para ejecutar pruebas de integraci贸n en paralelo
integration-test-job:
  stage: test
  image: gradle:jdk17
  script:
    - echo "Running integration tests."

# Job para desplegar la aplicaci贸n en producci贸n
deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
